name: file_manager
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter

  flutter_localizations:
    sdk: flutter

  # Dart
  intl: ^0.19.0
  path: ^1.9.0
  async: ^2.11.0
  collection: 1.18.0

  # Flutter
  go_router: ^14.2.7
  path_provider: ^2.1.4
  cross_file: ^0.3.4+2
  url_launcher: ^6.3.0

  # Flutter Community

  # 3rd Party
  flutter_bloc: ^8.1.6
  hydrated_bloc: ^9.1.5

  photo_view: ^0.15.0
  flutter_svg: ^2.0.10+1

  google_fonts: ^6.2.1
  timeago: ^3.7.0
  image: ^4.2.0
  permission_handler: ^11.3.1
  app_settings: ^5.1.1
  open_file: ^3.5.4
  video_compress: ^3.1.3
  file: ^7.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  build_runner: ^2.4.12

  flutter_lints: ^4.0.0

  bloc_test: ^9.1.7

  flutter_gen_runner: ^5.7.0

flutter_gen:
  integrations:
    flutter_svg: true


flutter:
  uses-material-design: true

  generate: true

  assets:
    - assets/svg/